export const GETUSERS = 'GETUSERS'
export const GETUSER = 'GETUSER'
export const GETREPOS = 'GETREPOS'
export const SETLOADING = 'SETLOADING'
export const CLEAR = 'CLEAR'
export const SETALERT = 'SETALERT'
export const REMOVEALERT = 'REMOVEALERT'
